use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!

target 'SourceModel_Example' do
  pod 'SourceModel', :path => '../'

  target 'SourceModel_Tests' do
    inherit! :search_paths

    
  end
end
